
spring:
  profiles:
    active:
      - dev 


---


server:
  port: 7001 


spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka-client




eureka:
  instance:
    host: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com/eureka/





--- 

server:
  port: 7001 


spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka-client




eureka:
  instance:
    host: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka7001.com/eureka/










